version: '3'
services:
  vueapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    networks:
      - default

networks:
  default:
    external:
      name: furimaHub-network
